export const listDummy = {
    1: {
        id: 1,
        title: 'test title 1',
        description: 'test description 1',
        added: '',
        modified: '',
        order: 1,
    },
    2: {
        id: 2,
        title: 'test title 2',
        description: 'test description 2',
        added: '',
        modified: '',
        order: 2,
    },
    3: {
        id: 3,
        title: 'test title 3',
        description: 'test description 3',
        added: '',
        modified: '',
        order: 3,
    },
    4: {
        id: 4,
        title: 'test title 4',
        description: 'test description 4',
        added: '',
        modified: '',
        order: 4,
    },
    5: {
        id: 5,
        title: 'test title 5',
        description: 'test description 5',
        added: '',
        modified: '',
        order: 5,
    },
};